// GENERATED by tests/pcms/p030/controller-bundle.mjs from protocol.js and
// controller-runtime.js. Do not edit; run the generator with --write instead.
// Classic script: the opaque-origin sandbox page cannot fetch ES modules (P030).
(() => {
"use strict";
const pcmsSandboxProtocol = (() => {
const OBJECT_GET_PROTOTYPE_OF = Object.getPrototypeOf;
const OBJECT_GET_OWN_PROPERTY_DESCRIPTORS = Object.getOwnPropertyDescriptors;
const OBJECT_GET_OWN_PROPERTY_SYMBOLS = Object.getOwnPropertySymbols;
const OBJECT_HAS_OWN = Object.hasOwn;
const OBJECT_ENTRIES = Object.entries;
const OBJECT_KEYS = Object.keys;
const OBJECT_FREEZE = Object.freeze;
const OBJECT_PROTOTYPE = Object.prototype;
const ARRAY_IS_ARRAY = Array.isArray;
const ARRAY_PROTOTYPE = Array.prototype;
const NUMBER_IS_FINITE = Number.isFinite;
const NativeWeakSet = WeakSet;
const NativeSet = Set;
const SET_HAS = Function.call.bind(Set.prototype.has);
const JSON_STRINGIFY = JSON.stringify.bind(JSON);
const TEXT_ENCODER = new TextEncoder();
const TEXT_ENCODE = TEXT_ENCODER.encode.bind(TEXT_ENCODER);

const SANDBOX_PROTOCOL_VERSION = 1;
const SANDBOX_BOOTSTRAP_TYPE = "pcms.sandbox.bootstrap";
const SANDBOX_MAX_MESSAGE_BYTES = 64 * 1024;
const SANDBOX_MAX_ENVELOPE_BYTES = 384 * 1024;
const SANDBOX_MAX_SOURCE_BYTES = 256 * 1024;
const SANDBOX_MAX_DEPTH = 10;
const SANDBOX_MAX_NODES = 4096;
const SANDBOX_MAX_STRING_LENGTH = 256 * 1024;
const SANDBOX_MAX_ID_LENGTH = 128;
const SANDBOX_MAX_CAPABILITY_NAME_LENGTH = 128;

const SANDBOX_ERROR_CODES = Object.freeze({
  PROTOCOL: "PCMS_SANDBOX_PROTOCOL",
  CAPABILITY_DENIED: "PCMS_SANDBOX_CAPABILITY_DENIED",
  CAPABILITY_FAILED: "PCMS_SANDBOX_CAPABILITY_FAILED",
  RPC_CAPACITY: "PCMS_SANDBOX_RPC_CAPACITY",
  CONTROLLER_INVALID: "PCMS_SANDBOX_CONTROLLER_INVALID",
  CONTROLLER_FAILED: "PCMS_SANDBOX_CONTROLLER_FAILED",
  NOT_READY: "PCMS_SANDBOX_NOT_READY",
  DISPOSED: "PCMS_SANDBOX_DISPOSED",
  TIMEOUT: "PCMS_SANDBOX_TIMEOUT"
});

const SAFE_ERROR_MESSAGES = Object.freeze({
  [SANDBOX_ERROR_CODES.PROTOCOL]: "Sandbox protocol violation",
  [SANDBOX_ERROR_CODES.CAPABILITY_DENIED]: "Capability is not granted",
  [SANDBOX_ERROR_CODES.CAPABILITY_FAILED]: "Capability call failed",
  [SANDBOX_ERROR_CODES.RPC_CAPACITY]: "Sandbox RPC capacity is exhausted",
  [SANDBOX_ERROR_CODES.CONTROLLER_INVALID]: "Dynamic controller is invalid",
  [SANDBOX_ERROR_CODES.CONTROLLER_FAILED]: "Dynamic controller operation failed",
  [SANDBOX_ERROR_CODES.NOT_READY]: "Sandbox controller is not ready",
  [SANDBOX_ERROR_CODES.DISPOSED]: "Sandbox controller is disposed",
  [SANDBOX_ERROR_CODES.TIMEOUT]: "Sandbox operation timed out"
});

const STABLE_ERROR_CODES = OBJECT_FREEZE(Object.values(SANDBOX_ERROR_CODES));
const STABLE_ERROR_CODE_SET = new NativeSet(STABLE_ERROR_CODES);
const FORBIDDEN_KEYS = new NativeSet(["__proto__", "prototype", "constructor"]);

class SandboxProtocolError extends Error {
  constructor(code, message = SAFE_ERROR_MESSAGES[code] || SAFE_ERROR_MESSAGES[SANDBOX_ERROR_CODES.PROTOCOL]) {
    super(message);
    this.name = "SandboxProtocolError";
    this.code = code;
  }
}

function fail(code = SANDBOX_ERROR_CODES.PROTOCOL) {
  throw new SandboxProtocolError(code);
}

function isPlainObject(value) {
  if (value === null || typeof value !== "object" || ARRAY_IS_ARRAY(value)) return false;
  const prototype = OBJECT_GET_PROTOTYPE_OF(value);
  return prototype === OBJECT_PROTOTYPE || prototype === null;
}

function setHas(set, value) {
  return SET_HAS(set, value);
}

function assertExactKeys(value, expected) {
  const actual = OBJECT_KEYS(value);
  if (actual.length !== expected.length) fail();
  for (let index = 0; index < expected.length; index += 1) {
    if (!OBJECT_HAS_OWN(value, expected[index])) fail();
  }
}

function sandboxSerializedBytes(value) {
  return TEXT_ENCODE(JSON_STRINGIFY(value)).byteLength;
}

function cloneSandboxJson(value, {
  maxBytes = SANDBOX_MAX_MESSAGE_BYTES,
  maxDepth = SANDBOX_MAX_DEPTH,
  maxNodes = SANDBOX_MAX_NODES,
  maxStringLength = SANDBOX_MAX_STRING_LENGTH
} = {}) {
  const ancestors = new NativeWeakSet();
  let nodes = 0;

  const visit = (input, depth) => {
    nodes += 1;
    if (nodes > maxNodes || depth > maxDepth) fail();
    if (input === null || typeof input === "boolean") return input;
    if (typeof input === "number") {
      if (!NUMBER_IS_FINITE(input)) fail();
      return input;
    }
    if (typeof input === "string") {
      if (input.length > maxStringLength) fail();
      return input;
    }
    if (typeof input !== "object") fail();
    if (ancestors.has(input)) fail();
    if (OBJECT_GET_OWN_PROPERTY_SYMBOLS(input).length) fail();

    ancestors.add(input);
    try {
      const descriptors = OBJECT_GET_OWN_PROPERTY_DESCRIPTORS(input);
      if (ARRAY_IS_ARRAY(input)) {
        if (OBJECT_GET_PROTOTYPE_OF(input) !== ARRAY_PROTOTYPE) fail();
        const out = new Array(input.length);
        for (const [key, descriptor] of OBJECT_ENTRIES(descriptors)) {
          if (key === "length") continue;
          if (!/^(0|[1-9][0-9]*)$/.test(key)
              || Number(key) >= input.length
              || !descriptor.enumerable
              || !OBJECT_HAS_OWN(descriptor, "value")) fail();
        }
        for (let index = 0; index < input.length; index += 1) {
          const descriptor = descriptors[String(index)];
          if (!descriptor || !OBJECT_HAS_OWN(descriptor, "value")) fail();
          out[index] = visit(descriptor.value, depth + 1);
        }
        return out;
      }

      if (!isPlainObject(input)) fail();
      const out = {};
      for (const [key, descriptor] of OBJECT_ENTRIES(descriptors)) {
        if (setHas(FORBIDDEN_KEYS, key)
            || key.length > 256
            || !descriptor.enumerable
            || !OBJECT_HAS_OWN(descriptor, "value")) fail();
        out[key] = visit(descriptor.value, depth + 1);
      }
      return out;
    } finally {
      ancestors.delete(input);
    }
  };

  const cloned = visit(value, 0);
  if (sandboxSerializedBytes(cloned) > maxBytes) fail();
  return cloned;
}

function assertSandboxId(value, label = "id") {
  if (typeof value !== "string" || value.length < 1 || value.length > SANDBOX_MAX_ID_LENGTH) {
    throw new SandboxProtocolError(SANDBOX_ERROR_CODES.PROTOCOL, label + " is invalid");
  }
  return value;
}

function assertSandboxRpcName(value, label = "RPC name") {
  if (typeof value !== "string"
      || value.length < 1
      || value.length > SANDBOX_MAX_CAPABILITY_NAME_LENGTH
      || setHas(FORBIDDEN_KEYS, value)) {
    throw new SandboxProtocolError(SANDBOX_ERROR_CODES.PROTOCOL, label + " is invalid");
  }
  return value;
}

function validateSandboxBootstrap(value) {
  const message = cloneSandboxJson(value, { maxBytes: 4096, maxDepth: 3, maxNodes: 32, maxStringLength: 256 });
  if (!isPlainObject(message)
      || message.type !== SANDBOX_BOOTSTRAP_TYPE
      || message.version !== SANDBOX_PROTOCOL_VERSION) fail();
  assertSandboxId(message.sessionId, "sessionId");
  assertExactKeys(message, ["type", "version", "sessionId"]);
  return message;
}

function validateSandboxPortMessage(value, expectedSessionId) {
  const message = cloneSandboxJson(value, { maxBytes: SANDBOX_MAX_ENVELOPE_BYTES });
  if (!isPlainObject(message) || message.version !== SANDBOX_PROTOCOL_VERSION) fail();
  assertSandboxId(message.sessionId, "sessionId");
  if (message.sessionId !== expectedSessionId) fail();
  assertSandboxRpcName(message.type, "message type");

  switch (message.type) {
    case "ready":
      assertExactKeys(message, ["version", "sessionId", "type"]);
      return message;
    case "request":
      assertSandboxId(message.requestId, "requestId");
      assertSandboxRpcName(message.method, "method");
      cloneSandboxJson(message.params ?? {}, { maxBytes: SANDBOX_MAX_ENVELOPE_BYTES });
      assertExactKeys(message, ["version", "sessionId", "type", "requestId", "method", "params"]);
      return message;
    case "response":
      assertSandboxId(message.requestId, "requestId");
      if (typeof message.ok !== "boolean") fail();
      if (message.ok) {
        if (!OBJECT_HAS_OWN(message, "result")) fail();
        cloneSandboxJson(message.result, { maxBytes: SANDBOX_MAX_MESSAGE_BYTES });
        assertExactKeys(message, ["version", "sessionId", "type", "requestId", "ok", "result"]);
      } else {
        validateSandboxError(message.error);
        assertExactKeys(message, ["version", "sessionId", "type", "requestId", "ok", "error"]);
      }
      return message;
    case "capability.call":
      assertSandboxId(message.callId, "callId");
      assertSandboxRpcName(message.capability, "capability");
      cloneSandboxJson(message.args ?? {}, { maxBytes: SANDBOX_MAX_MESSAGE_BYTES });
      assertExactKeys(message, ["version", "sessionId", "type", "callId", "capability", "args"]);
      return message;
    case "capability.result":
      assertSandboxId(message.callId, "callId");
      if (typeof message.ok !== "boolean") fail();
      if (message.ok) {
        if (!OBJECT_HAS_OWN(message, "result")) fail();
        cloneSandboxJson(message.result, { maxBytes: SANDBOX_MAX_MESSAGE_BYTES });
        assertExactKeys(message, ["version", "sessionId", "type", "callId", "ok", "result"]);
      } else {
        validateSandboxError(message.error);
        assertExactKeys(message, ["version", "sessionId", "type", "callId", "ok", "error"]);
      }
      return message;
    default:
      fail();
  }
}

function validateSandboxError(error) {
  if (!isPlainObject(error)
      || typeof error.code !== "string"
      || !setHas(STABLE_ERROR_CODE_SET, error.code)
      || typeof error.message !== "string"
      || error.message.length > 256) fail();
  assertExactKeys(error, ["code", "message"]);
  return error;
}

function safeSandboxError(code) {
  const safeCode = setHas(STABLE_ERROR_CODE_SET, code) ? code : SANDBOX_ERROR_CODES.PROTOCOL;
  return OBJECT_FREEZE({ code: safeCode, message: SAFE_ERROR_MESSAGES[safeCode] });
}
return Object.freeze({ SANDBOX_PROTOCOL_VERSION, SANDBOX_BOOTSTRAP_TYPE, SANDBOX_MAX_MESSAGE_BYTES, SANDBOX_MAX_ENVELOPE_BYTES, SANDBOX_MAX_SOURCE_BYTES, SANDBOX_MAX_DEPTH, SANDBOX_MAX_NODES, SANDBOX_MAX_STRING_LENGTH, SANDBOX_MAX_ID_LENGTH, SANDBOX_MAX_CAPABILITY_NAME_LENGTH, SANDBOX_ERROR_CODES, SandboxProtocolError, sandboxSerializedBytes, cloneSandboxJson, assertSandboxId, assertSandboxRpcName, validateSandboxBootstrap, validateSandboxPortMessage, validateSandboxError, safeSandboxError });
})();
const pcmsSandboxControllerRuntime = (() => {
const { SANDBOX_ERROR_CODES, SANDBOX_MAX_MESSAGE_BYTES, SANDBOX_MAX_SOURCE_BYTES, SANDBOX_PROTOCOL_VERSION, SandboxProtocolError, assertSandboxRpcName, cloneSandboxJson, safeSandboxError, validateSandboxBootstrap, validateSandboxPortMessage } = pcmsSandboxProtocol;

const OBJECT_GET_PROTOTYPE_OF = Object.getPrototypeOf;
const OBJECT_GET_OWN_PROPERTY_DESCRIPTORS = Object.getOwnPropertyDescriptors;
const OBJECT_GET_OWN_PROPERTY_SYMBOLS = Object.getOwnPropertySymbols;
const OBJECT_HAS_OWN = Object.hasOwn;
const OBJECT_ENTRIES = Object.entries;
const OBJECT_FREEZE = Object.freeze;
const OBJECT_PROTOTYPE = Object.prototype;
const ARRAY_IS_ARRAY = Array.isArray;
const TEXT_ENCODER = new TextEncoder();
const TEXT_ENCODE = TEXT_ENCODER.encode.bind(TEXT_ENCODER);
const NativePromise = Promise;

function protocolError(code) {
  return new SandboxProtocolError(code);
}

function jsonResult(value) {
  return cloneSandboxJson(value === undefined ? null : value, { maxBytes: SANDBOX_MAX_MESSAGE_BYTES });
}

function validateController(controller) {
  if (controller === null || typeof controller !== "object" || ARRAY_IS_ARRAY(controller)) {
    throw protocolError(SANDBOX_ERROR_CODES.CONTROLLER_INVALID);
  }
  const prototype = OBJECT_GET_PROTOTYPE_OF(controller);
  if (prototype !== OBJECT_PROTOTYPE && prototype !== null) {
    throw protocolError(SANDBOX_ERROR_CODES.CONTROLLER_INVALID);
  }
  if (OBJECT_GET_OWN_PROPERTY_SYMBOLS(controller).length) {
    throw protocolError(SANDBOX_ERROR_CODES.CONTROLLER_INVALID);
  }
  const descriptors = OBJECT_GET_OWN_PROPERTY_DESCRIPTORS(controller);
  for (const [name, descriptor] of OBJECT_ENTRIES(descriptors)) {
    assertSandboxRpcName(name, "controller method");
    if (!descriptor.enumerable
        || !OBJECT_HAS_OWN(descriptor, "value")
        || typeof descriptor.value !== "function") {
      throw protocolError(SANDBOX_ERROR_CODES.CONTROLLER_INVALID);
    }
  }
  return controller;
}

function installSandboxControllerRuntime({
  windowRef = globalThis.window,
  FunctionCtor = globalThis.Function,
  capabilityTimeoutMs = 15_000,
  setTimer = globalThis.setTimeout?.bind(globalThis),
  clearTimer = globalThis.clearTimeout?.bind(globalThis),
  queueTask = globalThis.queueMicrotask?.bind(globalThis)
} = {}) {
  if (!windowRef?.addEventListener || !windowRef?.removeEventListener || !windowRef?.location) {
    throw new TypeError("Sandbox controller runtime requires a Window-like object");
  }
  if (typeof FunctionCtor !== "function"
      || typeof setTimer !== "function"
      || typeof clearTimer !== "function"
      || typeof queueTask !== "function") {
    throw new TypeError("Sandbox controller runtime prerequisites are unavailable");
  }

  let port = null;
  let postPortMessage = null;
  let closePort = null;
  let sessionId = null;
  let controller = null;
  let disposed = false;
  let capabilitySequence = 0;
  const pendingCapabilities = new Map();
  const pendingGet = pendingCapabilities.get.bind(pendingCapabilities);
  const pendingSet = pendingCapabilities.set.bind(pendingCapabilities);
  const pendingDelete = pendingCapabilities.delete.bind(pendingCapabilities);
  const pendingValues = pendingCapabilities.values.bind(pendingCapabilities);
  const pendingClear = pendingCapabilities.clear.bind(pendingCapabilities);

  function rejectPending(code) {
    for (const pending of pendingValues()) {
      clearTimer(pending.timer);
      pending.reject(protocolError(code));
    }
    pendingClear();
  }

  function shutdown(code = SANDBOX_ERROR_CODES.DISPOSED) {
    if (disposed) return;
    disposed = true;
    rejectPending(code);
    try { closePort?.(); } catch {}
    port = null;
    postPortMessage = null;
    closePort = null;
  }

  function post(message) {
    if (disposed || !postPortMessage) throw protocolError(SANDBOX_ERROR_CODES.DISPOSED);
    postPortMessage(message);
  }

  function sendResponse(requestId, ok, value) {
    const base = { version: SANDBOX_PROTOCOL_VERSION, sessionId, type: "response", requestId, ok };
    post(ok
      ? { ...base, result: jsonResult(value) }
      : { ...base, error: safeSandboxError(value) });
  }

  function callCapability(capability, args = {}) {
    if (disposed) return NativePromise.reject(protocolError(SANDBOX_ERROR_CODES.DISPOSED));
    try {
      assertSandboxRpcName(capability, "capability");
      const safeArgs = cloneSandboxJson(args, { maxBytes: SANDBOX_MAX_MESSAGE_BYTES });
      const callId = "cap-" + (++capabilitySequence);
      return new NativePromise((resolve, reject) => {
        const timer = setTimer(() => {
          pendingDelete(callId);
          reject(protocolError(SANDBOX_ERROR_CODES.TIMEOUT));
        }, capabilityTimeoutMs);
        pendingSet(callId, { resolve, reject, timer });
        post({
          version: SANDBOX_PROTOCOL_VERSION,
          sessionId,
          type: "capability.call",
          callId,
          capability,
          args: safeArgs
        });
      });
    } catch (error) {
      return NativePromise.reject(error);
    }
  }

  const api = OBJECT_FREEZE({
    version: SANDBOX_PROTOCOL_VERSION,
    call: callCapability
  });

  async function loadController(params) {
    if (controller) throw protocolError(SANDBOX_ERROR_CODES.CONTROLLER_INVALID);
    const safeParams = cloneSandboxJson(params, {
      maxBytes: SANDBOX_MAX_SOURCE_BYTES + SANDBOX_MAX_MESSAGE_BYTES + 4096
    });
    const source = safeParams.source;
    if (typeof source !== "string"
        || !source.trim()
        || TEXT_ENCODE(source).byteLength > SANDBOX_MAX_SOURCE_BYTES) {
      throw protocolError(SANDBOX_ERROR_CODES.CONTROLLER_INVALID);
    }

    let factory;
    try {
      factory = FunctionCtor('"use strict"; return (' + source + '\n);')();
    } catch {
      throw protocolError(SANDBOX_ERROR_CODES.CONTROLLER_INVALID);
    }
    if (typeof factory !== "function") {
      throw protocolError(SANDBOX_ERROR_CODES.CONTROLLER_INVALID);
    }

    try {
      const candidate = await factory(api);
      controller = OBJECT_FREEZE(validateController(candidate));
      const startResult = typeof controller.start === "function"
        ? await controller.start(cloneSandboxJson(safeParams.initial ?? null, { maxBytes: SANDBOX_MAX_MESSAGE_BYTES }))
        : null;
      return jsonResult(startResult);
    } catch (error) {
      controller = null;
      if (error instanceof SandboxProtocolError) throw error;
      throw protocolError(SANDBOX_ERROR_CODES.CONTROLLER_FAILED);
    }
  }

  async function invokeController(params) {
    if (!controller) throw protocolError(SANDBOX_ERROR_CODES.NOT_READY);
    const safeParams = cloneSandboxJson(params, { maxBytes: SANDBOX_MAX_MESSAGE_BYTES });
    const method = assertSandboxRpcName(safeParams.method, "controller method");
    if (method === "start"
        || method === "dispose"
        || !OBJECT_HAS_OWN(controller, method)
        || typeof controller[method] !== "function") {
      throw protocolError(SANDBOX_ERROR_CODES.CONTROLLER_INVALID);
    }
    try {
      return jsonResult(await controller[method](safeParams.args ?? null));
    } catch (error) {
      if (error instanceof SandboxProtocolError) throw error;
      throw protocolError(SANDBOX_ERROR_CODES.CONTROLLER_FAILED);
    }
  }

  async function disposeController() {
    if (!controller) return null;
    const active = controller;
    controller = null;
    try {
      return typeof active.dispose === "function" ? jsonResult(await active.dispose()) : null;
    } catch {
      throw protocolError(SANDBOX_ERROR_CODES.CONTROLLER_FAILED);
    }
  }

  async function onPortMessage(event) {
    if (disposed) return;
    let message;
    try {
      message = validateSandboxPortMessage(event?.data, sessionId);
    } catch {
      shutdown(SANDBOX_ERROR_CODES.PROTOCOL);
      return;
    }

    if (message.type === "capability.result") {
      const pending = pendingGet(message.callId);
      if (!pending) {
        shutdown(SANDBOX_ERROR_CODES.PROTOCOL);
        return;
      }
      pendingDelete(message.callId);
      clearTimer(pending.timer);
      if (message.ok) pending.resolve(jsonResult(message.result));
      else pending.reject(protocolError(message.error.code));
      return;
    }

    if (message.type !== "request") {
      shutdown(SANDBOX_ERROR_CODES.PROTOCOL);
      return;
    }

    try {
      let result;
      if (message.method === "controller.load") result = await loadController(message.params);
      else if (message.method === "controller.invoke") result = await invokeController(message.params);
      else if (message.method === "controller.dispose") result = await disposeController();
      else throw protocolError(SANDBOX_ERROR_CODES.PROTOCOL);
      sendResponse(message.requestId, true, result);
      if (message.method === "controller.dispose") queueTask(() => shutdown());
    } catch (error) {
      const code = error instanceof SandboxProtocolError
        ? error.code
        : SANDBOX_ERROR_CODES.CONTROLLER_FAILED;
      sendResponse(message.requestId, false, code);
      if (message.method === "controller.dispose") queueTask(() => shutdown());
    }
  }

  function onBootstrap(event) {
    if (disposed || port) return;
    if (event?.source !== windowRef.parent || event?.origin !== windowRef.location.origin) return;

    let bootstrap;
    try {
      bootstrap = validateSandboxBootstrap(event.data);
      if (event?.ports?.length !== 1 || !event.ports[0]) return;
    } catch {
      return;
    }

    const candidatePort = event.ports[0];
    if (typeof candidatePort.postMessage !== "function"
        || typeof candidatePort.close !== "function"
        || typeof candidatePort.addEventListener !== "function") return;

    sessionId = bootstrap.sessionId;
    port = candidatePort;
    postPortMessage = candidatePort.postMessage.bind(candidatePort);
    closePort = candidatePort.close.bind(candidatePort);
    windowRef.removeEventListener("message", onBootstrap);
    candidatePort.addEventListener("message", onPortMessage);
    candidatePort.start?.();
    post({ version: SANDBOX_PROTOCOL_VERSION, sessionId, type: "ready" });
  }

  windowRef.addEventListener("message", onBootstrap);

  return OBJECT_FREEZE({
    get bootstrapped() { return Boolean(port); },
    get disposed() { return disposed; },
    dispose() {
      windowRef.removeEventListener("message", onBootstrap);
      shutdown();
    }
  });
}
return Object.freeze({ installSandboxControllerRuntime });
})();
pcmsSandboxControllerRuntime.installSandboxControllerRuntime();
})();
