import assert from "node:assert/strict";
import { createPersonaPlatform } from "../lib/persona-platform.js";
import { routeTestContext } from "../lib/persona-intelligence.js";

const SOURCE_PERSONA_UID = "70000000-0000-4000-8000-000000000001";
const CREATED_UIDS = Array.from({ length: 8 }, (_, index) =>
  `70000000-0000-4000-9000-${String(index + 2).padStart(12, "0")}`);
let createSequence = 0;
const createProfiles = [];

let state={global:{enforcePrivacyControls:true,strictProxyVerification:true},profiles:{p1:{containerId:"p1",personaUid:SOURCE_PERSONA_UID,name:"Research",managed:true,owned:true,routeId:"r1",killSwitch:true,scriptIds:[]}},routes:{r1:{id:"r1",name:"Mullvad NL",provider:"mullvad",type:"socks",host:"1.2.3.4",port:1080,proxyDNS:true,enabled:true}},scripts:{},workflows:{}};
const calls=[];
let cachedRouteTest = null;
let routeMutationOptions;
let createMutationOptions;
const personaManager={listContainers:async()=>[{cookieStoreId:"p1",name:"Research",color:"purple",icon:"tree"}],open:async(...args)=>calls.push(["open",...args]),duplicate:async(...args)=>calls.push(["duplicate",...args]),clone:async(...args)=>calls.push(["clone",...args]),archive:async(...args)=>calls.push(["archive",...args]),fullWipe:async(...args)=>calls.push(["wipe",...args]),remove:async(...args)=>calls.push(["remove",...args]),destroy:async(...args)=>calls.push(["destroy",...args]),cleanupExpired:async()=>[],updateIdentity:async(...args)=>calls.push(["identity",...args]),updateProfileRoute:async(id,routeId,options,validate)=>{routeMutationOptions=options;validate?.(state,state.profiles[id]);state.profiles[id].routeId=routeId;return structuredClone(state.profiles[id]);},resolvePersonaUid:async(uid)=>({status:uid===SOURCE_PERSONA_UID?"ok":"missing",personaUid:uid,cookieStoreId:uid===SOURCE_PERSONA_UID?"p1":null,profile:uid===SOURCE_PERSONA_UID?state.profiles.p1:null}),create:async({name,profile},options)=>{createMutationOptions=options;options?.validateProfile?.(state,profile);createProfiles.push(structuredClone(profile));const id="p2";state.profiles[id]={...profile,personaUid:profile?.personaUid||CREATED_UIDS[createSequence++],containerId:id,name,managed:true};return{profile:state.profiles[id],container:{cookieStoreId:id,name,color:"blue",icon:"fingerprint"}};}};
const cookieService={list:async()=>[{name:"a",value:"b"}],importRecords:async(id,rows)=>({imported:rows.length,failed:0})};
const storageService={summary:async()=>({activeTabs:1}),inspect:async()=>({activeTabs:1}),clear:async()=>({}),clearCookies:async()=>({}),clearSiteData:async()=>({})};
const securityState={ready:true,privacySafe:true,proxyControl:"controllable_by_this_extension"};
const platformDeps={getState:async()=>state,setState:async(next)=>{state=structuredClone(next);return state;},personaManager,cookieService,storageService,browserApi:{tabs:{query:async()=>[{cookieStoreId:"p1"}]}},securityState,getRouteTest:async()=>cachedRouteTest,runRouteTest:async()=>({ok:true}),appVersion:"0.7.0"};
const platform=createPersonaPlatform(platformDeps);
const cards=await platform.list();
assert.equal(cards[0].name,"Research");
assert.equal(cards[0].id,"p1");
assert.equal(cards[0].cookieStoreId,"p1");
assert.equal(cards[0].personaUid,SOURCE_PERSONA_UID);
assert.equal(cards[0].activeTabs,1);
assert.equal(cards[0].health.status,"untested");
cachedRouteTest={context:routeTestContext(state.profiles.p1,state.routes.r1,{...securityState,privacyRequired:true,strictProxyVerification:true}),result:{ok:true,checkedAt:new Date().toISOString(),data:{ip:"203.0.113.4"},dns:{checked:true,leaking:false}}};
assert.equal((await platform.get("p1")).health.exitIp,"203.0.113.4");
state.global.strictProxyVerification=false;
assert.equal((await platform.getRouteStatus("p1")).exitIp,null,"weaker proxy verification must invalidate management health");
state.global.strictProxyVerification=true;
state.routes.r1.host="1.2.3.5";
assert.equal((await platform.getRouteStatus("p1")).exitIp,null,"route edits invalidate the management projection");
state.routes.r1.host="1.2.3.4";
securityState.privacySafe=false;
assert.equal((await platform.get("p1")).health.status,"error","privacy failure overrides a cached success");
securityState.privacySafe=true;
cachedRouteTest=null;
const bytes=await platform.export("p1");
const preview=await platform.inspectImport(bytes);
const imported=await platform.import(bytes);
assert.equal(imported.profile.containerId,"p2");
const forgedPreview = {...preview, route:{mode:"direct"}, settings:{...preview.settings,killSwitch:false,blockLocalNetwork:false}};
const beforeForgedImport=structuredClone(state);
const createdBeforeForgedImport=createProfiles.length;
await assert.rejects(platform.import(forgedPreview),/file is too small/);
assert.deepEqual(state,beforeForgedImport,"a previously inspected or caller-built preview must be parsed again before mutation");
assert.equal(createProfiles.length,createdBeforeForgedImport,"rejected preview must not create a Persona");

const relaxedState=structuredClone(state);
relaxedState.profiles.p1.killSwitch=false;
relaxedState.profiles.p1.blockLocalNetwork=false;
const relaxedBytes=await import("../lib/persona-package.js").then(({createPersonaPackage})=>createPersonaPackage({profileId:"p1",state:relaxedState,container:{name:"Research",color:"purple",icon:"tree"},appVersion:"0.7.0"}));
await platform.import(relaxedBytes);
assert.equal(createProfiles.at(-1).killSwitch, true, "portable packages cannot silently disable the new Persona's kill switch");
assert.equal(createProfiles.at(-1).blockLocalNetwork, true, "portable packages cannot silently disable LAN blocking");
assert.notEqual(imported.profile.personaUid,SOURCE_PERSONA_UID,"portable import becomes a new logical Persona");
assert.equal(createProfiles[0].personaUid,null,"portable package does not supply the source UID to create");
assert.equal(imported.routeId,"r1");
assert.equal(imported.cookies.imported,0,"cookie import must require explicit opt-in");
assert.equal(imported.cookies.excluded,0);
const sensitiveBytes=await platform.export("p1",{cookies:true});
const sensitivePreview=await platform.inspectImport(sensitiveBytes);
const importedWithCookies=await platform.import(sensitiveBytes,{importCookies:true});
assert.equal(importedWithCookies.cookies.imported,1);

const stateBeforeMalformedImport=structuredClone(state);
const personasBeforeMalformedImport=createProfiles.length;
await assert.rejects(platform.import(new Uint8Array([1,2,3])),/file is too small/);
assert.deepEqual(state,stateBeforeMalformedImport,"malformed inspection must not mutate persisted state");
assert.equal(createProfiles.length,personasBeforeMalformedImport,"malformed inspection must not create a Persona");

const failedInspector=createPersonaPlatform({
  ...platformDeps,
  inspectPackage:async()=>{throw new Error("Package inspection worker is unavailable");}
});
await assert.rejects(failedInspector.import(bytes),/worker is unavailable/);
assert.deepEqual(state,stateBeforeMalformedImport,"worker inspection failure must not mutate persisted state");
assert.equal(createProfiles.length,personasBeforeMalformedImport,"worker inspection failure must not create a Persona");

const directState=structuredClone(state);
directState.profiles.p1.routeId="__direct__";
const directBytes=await import("../lib/persona-package.js").then(({createPersonaPackage})=>createPersonaPackage({profileId:"p1",state:directState,container:{name:"Research",color:"purple",icon:"tree"},appVersion:"0.7.0"}));
const blockedDirect=await platform.import(directBytes);
assert.equal(blockedDirect.profile.routeId,"__block__","package Direct intent cannot authorize Direct routing");
assert.equal(blockedDirect.profile.killSwitch,true);
assert.equal(blockedDirect.profile.blockLocalNetwork,true);
const optedInDirect=await platform.import(directBytes,{allowDirect:true});
assert.equal(optedInDirect.profile.routeId,"__direct__","Direct remains available only after an explicit import opt-in");
const temporary=await platform.create({name:"Agent-Test",temporary:true,ttlHours:24});
assert.equal(temporary.profile.status,"temporary");
assert.ok(temporary.profile.expiresAt);
await assert.rejects(platform.create({name:"   ",temporary:true}),/must not be empty/);
const routes=await platform.listRoutes();
assert.equal(routes.find((route)=>route.id==="r1").username,undefined,"route credentials must never cross the PCMS facade");
assert.equal((await platform.getRoute("__block__")).name,"Block");
await assert.rejects(platform.assignRoute("p1","__direct__"),/allowDirect/);
await assert.rejects(platform.assignRoute("p1","missing"),/Route not found/);
state.routes.disabled={id:"disabled",name:"Disabled",enabled:false,username:"secret",password:"secret"};
await assert.rejects(platform.assignRoute("p1","disabled"),/disabled/);
const direct=await platform.assignRoute("p1","__direct__",{allowDirect:true});
assert.equal(direct.route.id,"__direct__");
assert.equal(direct.profile.routeId,"__direct__");
await platform.assignRoute("p1","r1",{expectedRevision:9,expectedBootId:"boot-9"});
assert.equal(routeMutationOptions.expectedRevision,9,"route assignment must preserve optimistic concurrency options");
assert.equal(routeMutationOptions.expectedBootId,"boot-9","route assignment must pass the boot precondition into the state mutation");
await assert.rejects(platform.create({name:"Unsafe",routeId:"__direct__"}),/allowDirect/);
await platform.create({name:"Direct",routeId:"__direct__",allowDirect:true});
assert.equal(typeof createMutationOptions.validateProfile,"function","platform create must revalidate route selection in the queued manager mutation");
assert.equal(createMutationOptions.granular,true,"Persona creation must pass its narrow Direct grant into the commit gate");
assert.equal(createMutationOptions.allowDirect,true);
await platform.create({name:"Direct via options",routeId:"__direct__"},{allowDirect:true});
await assert.rejects(platform.create({name:"Missing",routeId:"missing"}),/Route not found/);
state.profiles.p1.routeId="__direct__";
await assert.rejects(platform.clone("p1",{}),/allowDirect/);
await platform.clone("p1",{allowDirect:true});
assert.equal(calls.at(-1)[0],"clone");
assert.equal(calls.at(-1)[1],"p1");
assert.equal(typeof calls.at(-1)[2].validateProfile,"function");
state.routes.r1.enabled=false;
await assert.rejects(platform.create({name:"Disabled",routeId:"r1"}),/disabled/);
assert.deepEqual(await platform.listWorkflows(),[]);
assert.equal(await platform.getWorkflow("missing"),null);
console.log("persona platform tests passed");
